import type { APIRoute } from 'astro';
import { createHash } from 'node:crypto';
import { commandDefs, tree } from '../lib/content';
import { siteHost } from '../site.config.ts';
import pkg from '../../package.json';

export const prerender = true;

// Build-time cache version that drives the "update available" toast (see
// Layout.astro). It changes whenever the data the worker caches changes — the
// command registry or the virtual filesystem — and whenever the package version
// is bumped for an app-only release. A stable version means a stable `sw.js`,
// so the browser detects no update and shows no toast.
const VERSION =
  `${pkg.version}-` +
  createHash('sha256')
    .update(JSON.stringify(commandDefs))
    .update(JSON.stringify(tree))
    .digest('hex')
    .slice(0, 8);

// The service worker source. Kept as a build-time template (rather than a static
// public/sw.js) only so the cache name can carry the build version above; the
// logic itself is plain runtime JS.
const SW = `/**
 * Service worker for ${siteHost}.
 *
 * Caches the externalised shell data (/shell-fs.json, /shell-commands.json)
 * so it is fetched once and shared across page navigations. Registered by
 * Layout.astro, which also drives the "update available" toast.
 *
 * Generated by src/pages/sw.js.ts; CACHE carries the build version.
 */

const CACHE = 'ltsh-${VERSION}';
const SHELL_DATA = ['/shell-fs.json', '/shell-commands.json'];

self.addEventListener('install', (event) => {
  // Precache the shell data, but do NOT skipWaiting here: a freshly installed
  // worker stays in "waiting" so the page can offer an update toast first. It
  // activates only once the page posts SKIP_WAITING (see the message handler).
  event.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(SHELL_DATA))
      .catch(() => {}), // a failed precache must not block install
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The update toast posts SKIP_WAITING when the visitor clicks "reload"; the
// waiting worker then activates and takes control, and the page reloads on the
// resulting controllerchange.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

// Intercept ONLY the shell-data files; everything else passes straight through.
// Stale-while-revalidate: serve the cached copy instantly, refresh in background.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || !SHELL_DATA.includes(url.pathname)) return;
  event.respondWith(
    caches.open(CACHE).then((cache) =>
      cache.match(event.request).then((cached) => {
        const fresh = fetch(event.request)
          .then((res) => {
            if (res.ok) cache.put(event.request, res.clone());
            return res;
          })
          .catch(() => cached);
        return cached || fresh;
      }),
    ),
  );
});
`;

// Served at /sw.js. `no-cache` lets the browser revalidate the script on each
// update check (it already bypasses the HTTP cache for the SW script, but this
// is explicit and also covers any intermediary cache).
export const GET: APIRoute = () =>
  new Response(SW, {
    headers: {
      'content-type': 'text/javascript; charset=utf-8',
      'cache-control': 'no-cache',
    },
  });
